[package]
name = "icm20948"
version = "0.0.0"
license = "MIT OR Apache-2.0"
authors = ["Luke Wirtanen <WirtanenLuke@gmail.com>"]
edition = "2021"
rust-version = "1.61"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]





